services:
  - type: web
    name: sherise-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python seed.py && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FRONTEND_ORIGINS
        value: https://sherise-mobile-app.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: sherise-db
          property: connectionString

databases:
  - name: sherise-db
    plan: free
    maxConnections: 10